#!/usr/bin/env python

import os
import sys
from pathlib import Path
from typing import Optional


def print_header(text: str):
    print(f"\n{'=' * 60}")
    print(f"  {text}")
    print(f"{'=' * 60}\n")


def print_step(step: int, text: str):
    print(f"\n[Step {step}] {text}")
    print("-" * 60)


def check_dependencies() -> bool:
    required = [
        "transformers",
        "huggingface_hub",
        "onnxruntime",
        "optimum",
        "llama-cpp-python",
    ]

    missing = []
    for pkg in required:
        try:
            __import__(pkg.replace("-", "_"))
        except ImportError:
            missing.append(pkg)

    if missing:
        print("Missing required packages:")
        for pkg in missing:
            print(f"   - {pkg}")
        print("\nInstall with:")
        print(f"   pip install {' '.join(missing)}")
        return False

    print("All required packages are installed")
    return True


def get_user_input(prompt: str, default: Optional[str] = None) -> str:
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "

    user_input = input(prompt).strip()
    return user_input if user_input else default


def setup_codebert() -> dict:
    print_step(2, "CodeBERT Setup (Code Analysis)")
    print("CodeBERT is a pre-trained model for code understanding.")

    model_name = get_user_input(
        "CodeBERT model name",
        default="microsoft/codebert-base",
    )

    return {"CODEBERT_MODEL": model_name}


def setup_qwen() -> dict:
    print_step(3, "Qwen LLM Setup (Code Generation)")
    print("Qwen is a lightweight language model for code generation.")
    print("\nDefault: TheBloke/Qwen2-0.5B-Instruct-GGUF")

    use_default = get_user_input("Use default Qwen model? (y/n)", default="y")

    if use_default.lower() == "y":
        return {
            "HF_MODEL_REPO": "TheBloke/Qwen2-0.5B-Instruct-GGUF",
            "HF_MODEL_FILE": "qwen2-0.5b-instruct.Q4_K_M.gguf",
        }

    repo_id = get_user_input("Hugging Face repository ID")
    filename = get_user_input("Model filename (e.g., model.gguf)")

    return {
        "HF_MODEL_REPO": repo_id,
        "HF_MODEL_FILE": filename,
    }


def setup_cache() -> dict:
    print_step(4, "Model Cache Configuration")
    print("Models will be cached locally after first download.")

    cache_dir = get_user_input(
        "Cache directory path",
        default=".model_cache",
    )

    return {"MODEL_CACHE_DIR": cache_dir}


def create_env_file(config: dict, env_file: str = ".env"):
    print_step(5, "Creating .env file")

    existing_env = {}
    if os.path.exists(env_file):
        with open(env_file, "r") as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, value = line.strip().split("=", 1)
                    existing_env[key] = value

    existing_env.update(config)

    with open(env_file, "w") as f:
        f.write("# Hugging Face Models Configuration\n")
        f.write("# Auto-generated by setup_models.py\n\n")
        for key, value in sorted(existing_env.items()):
            f.write(f"{key}={value}\n")

    print(f"Created {env_file}")
    print("\nConfiguration saved:")
    for key, value in config.items():
        print(f"   {key}={value}")


def create_gitignore_entry():
    print_step(6, "Updating .gitignore")

    gitignore_file = ".gitignore"
    model_entries = [
        "# Model cache and local models",
        ".model_cache/",
        "*.gguf",
        "*.onnx",
    ]

    if os.path.exists(gitignore_file):
        with open(gitignore_file, "r") as f:
            content = f.read()

        if ".model_cache/" in content:
            print(".gitignore already has model entries")
            return

        with open(gitignore_file, "a") as f:
            f.write("\n# Model cache and local models\n")
            f.write(".model_cache/\n")
            f.write("*.gguf\n")
            f.write("*.onnx\n")
    else:
        with open(gitignore_file, "w") as f:
            for entry in model_entries:
                f.write(f"{entry}\n")

    print(f"Updated {gitignore_file}")


def download_models() -> bool:
    print_step(7, "Download Models Now?")

    response = get_user_input("Download models now? (y/n)", default="y")

    if response.lower() != "y":
        print("Skipped. Models will download on first run.")
        return False

    print("\nDownloading models...")

    try:
        from transformers import AutoModel, AutoTokenizer
        from huggingface_hub import hf_hub_download

        # read config from .env
        config = {}
        if os.path.exists(".env"):
            with open(".env", "r") as f:
                for line in f:
                    if "=" in line and not line.startswith("#"):
                        key, value = line.strip().split("=", 1)
                        config[key] = value

        cache_dir = config.get("MODEL_CACHE_DIR", ".model_cache")

        print("\nDownloading CodeBERT...")
        codebert_model = config.get("CODEBERT_MODEL", "microsoft/codebert-base")
        AutoModel.from_pretrained(codebert_model, cache_dir=cache_dir)
        AutoTokenizer.from_pretrained(codebert_model, cache_dir=cache_dir)
        print(f"CodeBERT downloaded: {codebert_model}")

        print("\nDownloading Qwen model...")
        qwen_repo = config.get("HF_MODEL_REPO", "TheBloke/Qwen2-0.5B-Instruct-GGUF")
        qwen_file = config.get("HF_MODEL_FILE", "qwen2-0.5b-instruct.Q4_K_M.gguf")
        hf_hub_download(repo_id=qwen_repo, filename=qwen_file, cache_dir=cache_dir)
        print(f"Qwen downloaded: {qwen_repo}/{qwen_file}")

        return True

    except Exception as e:
        print(f"Download failed: {e}")
        print("Models will be downloaded on first run.")
        return False


def show_summary():
    print_header("Setup Complete")

    print("Next steps:")
    print("1. Review .env file (if created)")
    print("2. Start the API:")
    print("   python services/app.py")
    print("\n3. Or use Docker:")
    print("   docker-compose up -d")

    print("\nDocumentation:")
    print("   - SETUP_COMPLETE.md (quick start)")
    print("   - COMPLETE_MODEL_MIGRATION_GUIDE.md (full guide)")

    print("\nTips:")
    print("   - Models cache locally after first download")
    print("   - Use custom models via environment variables")
    print("   - Run this script again to update configuration")


def main():
    print_header("RepoSense Model Setup Wizard")
    print("This wizard will help you configure Hugging Face models.\n")

    print_step(1, "Checking Dependencies")
    if not check_dependencies():
        print("\nSetup failed: please install missing packages")
        sys.exit(1)

    config = {}
    config.update(setup_codebert())
    config.update(setup_qwen())
    config.update(setup_cache())

    create_env_file(config)
    create_gitignore_entry()
    download_models()
    show_summary()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled")
        sys.exit(0)
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)